# Generated by Django 4.1.7 on 2023-02-26 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0013_remove_emprestimo_tempo_devolução'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='descrição',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='emprestimo',
            old_name='data_devolução',
            new_name='data_devolucao',
        ),
    ]
