# Generated by Django 4.1.7 on 2023-02-28 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0014_rename_descrição_categoria_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='img',
            field=models.ImageField(default=True, null=True, upload_to='capa_livro'),
        ),
    ]
