# Generated by Django 4.1.7 on 2023-02-28 22:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0016_emprestimo_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='avaliacao',
            field=models.CharField(blank=True, choices=[('PE', 'Péssimo'), ('RU', 'Ruim'), ('RE', 'Regular'), ('BO', 'Bom'), ('OT', 'Ótimo')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
